"""phase 8 milestone 3 commercial policy and internal notifications

Revision ID: 0b1d294dfb40
Revises: 8646da2df010
Create Date: 2026-07-26 09:03:57.079041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0b1d294dfb40'
down_revision = '8646da2df010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_commercial_policies',
    sa.Column('policy_code', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('warning_offsets_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notify_role_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_customer_contact', sa.Boolean(), nullable=False),
    sa.Column('past_due_start_days', sa.Integer(), nullable=False),
    sa.Column('payment_grace_days', sa.Integer(), nullable=False),
    sa.Column('auto_expire_after_grace', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('retired_date', sa.Date(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_code')
    )
    op.create_table('owner_internal_notifications',
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('installation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('assigned_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_role_code', sa.String(length=32), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('source_policy_code', sa.String(length=64), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_internal_notifications')
    op.drop_table('owner_commercial_policies')
    # ### end Alembic commands ###
