"""phase 8 milestone 5 manual activation approval and device slot ops

Revision ID: 0f8d55b753ed
Revises: 65397e1b63e1
Create Date: 2026-07-26 14:36:58.834452

"""
from alembic import op
import sqlalchemy as sa


revision = '0f8d55b753ed'
down_revision = '65397e1b63e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_activation_policies',
    sa.Column('policy_code', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('retired_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_code')
    )
    op.create_table('owner_device_slot_exceptions',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('extra_slots', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_pending_activations',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('device_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['owner_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_pending_activations')
    op.drop_table('owner_device_slot_exceptions')
    op.drop_table('owner_activation_policies')
    # ### end Alembic commands ###
