"""phase9r_m4_installation_license_label_index

Revision ID: 13944658bddf
Revises: f5959fdb9738
Create Date: 2026-08-04 09:29:53.946631

"""
from alembic import op
import sqlalchemy as sa


revision = '13944658bddf'
down_revision = 'f5959fdb9738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_owner_installations_license_id_installation_label', 'owner_installations', ['license_id', 'installation_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_owner_installations_license_id_installation_label', table_name='owner_installations')
    # ### end Alembic commands ###
