"""phase 9.5a commercial operations foundation

Revision ID: 3c0d51d82d8c
Revises: 0f8d55b753ed
Create Date: 2026-08-01 06:22:21.255422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3c0d51d82d8c'
down_revision = '0f8d55b753ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_commercial_operations_idempotency_keys',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('operation_code', sa.String(length=64), nullable=False),
    sa.Column('result_reference_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'operation_code', name='uq_commercial_ops_idempotency')
    )
    op.create_table('owner_commission_plans',
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('owner_daily_activity_snapshots',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=32), nullable=False),
    sa.Column('generation_status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.String(length=16), nullable=False),
    sa.Column('generated_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('source_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metric_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date')
    )
    op.create_table('owner_expense_categories',
    sa.Column('category_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('owner_commission_payout_batches',
    sa.Column('batch_reference', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_reference')
    )
    op.create_table('owner_commission_rule_versions',
    sa.Column('commission_plan_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_plan_id'], ['owner_commission_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_employee_profiles',
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('employment_start_date', sa.Date(), nullable=False),
    sa.Column('employment_end_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(length=16), nullable=False),
    sa.Column('manager_employee_profile_id', sa.UUID(), nullable=True),
    sa.Column('commission_plan_id', sa.UUID(), nullable=True),
    sa.Column('profile_image_reference', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_plan_id'], ['owner_commission_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['manager_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number'),
    sa.UniqueConstraint('staff_user_id')
    )
    op.create_table('owner_device_policy_profiles',
    sa.Column('profile_code', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('max_total_devices', sa.Integer(), nullable=True),
    sa.Column('approval_required_after_device_number', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('retired_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_code')
    )
    op.create_table('owner_employee_commission_plan_assignments',
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('commission_plan_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_plan_id'], ['owner_commission_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_employee_presence_sessions',
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('staff_session_id', sa.UUID(), nullable=False),
    sa.Column('app_instance_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['staff_session_id'], ['owner_staff_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_expenses',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('entered_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attachment_reference', sa.String(length=512), nullable=True),
    sa.Column('reversal_of_expense_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['owner_expense_categories.id'], ),
    sa.ForeignKeyConstraint(['entered_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_expense_id'], ['owner_expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_leads',
    sa.Column('organization_or_prospect_name', sa.String(length=200), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_employee_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_summary', sa.String(length=200), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_shared_management_notes',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_employee_profile_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_device_policy_platform_rules',
    sa.Column('device_policy_profile_id', sa.UUID(), nullable=False),
    sa.Column('platform_category', sa.String(length=16), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_policy_profile_id'], ['owner_device_policy_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_lead_assignments',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_lead_followups',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_lead_interactions',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_lead_notes',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('author_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_lead_product_interests',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_lead_status_history',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('changed_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_management_note_comments',
    sa.Column('management_note_id', sa.UUID(), nullable=False),
    sa.Column('author_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['management_note_id'], ['owner_shared_management_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_management_note_visibility_grants',
    sa.Column('management_note_id', sa.UUID(), nullable=False),
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['management_note_id'], ['owner_shared_management_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_customer_followups',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_customer_interactions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_customer_locations',
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('accuracy_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('manual_address', sa.Text(), nullable=True),
    sa.Column('reverse_geocoded_address', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(lead_id IS NOT NULL)::int + (customer_id IS NOT NULL)::int = 1', name='ck_customer_locations_exactly_one_owner'),
    sa.ForeignKeyConstraint(['captured_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['owner_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_quotes',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quote_number', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_table('owner_quote_lines',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('addon_id', sa.UUID(), nullable=True),
    sa.Column('price_version_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overridden_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(plan_id IS NOT NULL)::int + (addon_id IS NOT NULL)::int = 1', name='ck_owner_quote_lines_exactly_one_of_plan_addon'),
    sa.ForeignKeyConstraint(['addon_id'], ['owner_addons.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['owner_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_sales_orders',
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['owner_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('owner_commercial_invoices',
    sa.Column('sales_order_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['owner_sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('owner_sales_order_lines',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('addon_id', sa.UUID(), nullable=True),
    sa.Column('price_version_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overridden_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(plan_id IS NOT NULL)::int + (addon_id IS NOT NULL)::int = 1', name='ck_owner_sales_order_lines_exactly_one_of_plan_addon'),
    sa.ForeignKeyConstraint(['addon_id'], ['owner_addons.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['owner_sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_commercial_invoice_items',
    sa.Column('commercial_invoice_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('addon_id', sa.UUID(), nullable=True),
    sa.Column('price_version_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overridden_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(plan_id IS NOT NULL)::int + (addon_id IS NOT NULL)::int = 1', name='ck_owner_commercial_invoice_items_exactly_one_of_plan_addon'),
    sa.ForeignKeyConstraint(['addon_id'], ['owner_addons.id'], ),
    sa.ForeignKeyConstraint(['commercial_invoice_id'], ['owner_commercial_invoices.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_subscription_device_policy_overrides',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('max_total_devices', sa.Integer(), nullable=True),
    sa.Column('approval_required_after_device_number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_commercial_refunds',
    sa.Column('commercial_invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_record_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['commercial_invoice_id'], ['owner_commercial_invoices.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['payment_record_id'], ['owner_payment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_commission_ledger_entries',
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('commission_rule_version_id', sa.UUID(), nullable=False),
    sa.Column('source_commercial_invoice_id', sa.UUID(), nullable=False),
    sa.Column('source_payment_record_id', sa.UUID(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_or_fixed_applied', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_of_ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['commission_rule_version_id'], ['owner_commission_rule_versions.id'], ),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_ledger_entry_id'], ['owner_commission_ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['source_commercial_invoice_id'], ['owner_commercial_invoices.id'], ),
    sa.ForeignKeyConstraint(['source_payment_record_id'], ['owner_payment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_commission_ledger_one_entry_per_payment', 'owner_commission_ledger_entries', ['source_payment_record_id'], unique=True, postgresql_where=sa.text('reversal_of_ledger_entry_id IS NULL'))
    op.create_table('owner_commission_payout_lines',
    sa.Column('commission_payout_batch_id', sa.UUID(), nullable=False),
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('commission_ledger_entry_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_ledger_entry_id'], ['owner_commission_ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['commission_payout_batch_id'], ['owner_commission_payout_batches.id'], ),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['owner_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commission_ledger_entry_id', name='uq_commission_payout_one_per_entry')
    )
    op.add_column('owner_customers', sa.Column('converted_from_lead_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'owner_customers', 'owner_leads', ['converted_from_lead_id'], ['id'])
    op.add_column('owner_payment_records', sa.Column('commercial_invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'owner_payment_records', 'owner_commercial_invoices', ['commercial_invoice_id'], ['id'])
    op.add_column('owner_staff_sessions', sa.Column('refresh_token_hash', sa.String(length=128), nullable=True))
    op.add_column('owner_staff_sessions', sa.Column('refresh_token_family_id', sa.UUID(), nullable=True))
    op.add_column('owner_staff_sessions', sa.Column('access_token_last_issued_at', sa.DateTime(timezone=True), nullable=True))
    # server_default backfills existing rows (this table has real pre-existing
    # sessions from every prior phase's dev/test work) -- every session that
    # already exists was, by definition, a browser session before mobile
    # login existed, so WEB is the real, correct historical value, not an
    # arbitrary placeholder.
    op.add_column(
        'owner_staff_sessions',
        sa.Column('platform', sa.String(length=16), nullable=False, server_default='WEB'),
    )
    op.create_unique_constraint(None, 'owner_staff_sessions', ['refresh_token_hash'])
    op.add_column('owner_subscriptions', sa.Column('sales_order_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'owner_subscriptions', 'owner_sales_orders', ['sales_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: this codebase has no
    # naming_convention configured on Base.metadata (a real, pre-existing gap
    # -- every prior migration only ever created whole new tables, whose
    # DROP TABLE implicitly removes all constraints, so this is the first
    # migration to need a *named* constraint reference for a downgrade).
    # Real names below were confirmed against the live database
    # (Postgres's own default <table>_<column>_fkey/_key pattern), not
    # guessed -- see docs/owner/phase9_5a/migration-validation-report.md. ###
    op.drop_constraint('owner_subscriptions_sales_order_id_fkey', 'owner_subscriptions', type_='foreignkey')
    op.drop_column('owner_subscriptions', 'sales_order_id')
    op.drop_constraint('owner_staff_sessions_refresh_token_hash_key', 'owner_staff_sessions', type_='unique')
    op.drop_column('owner_staff_sessions', 'platform')
    op.drop_column('owner_staff_sessions', 'access_token_last_issued_at')
    op.drop_column('owner_staff_sessions', 'refresh_token_family_id')
    op.drop_column('owner_staff_sessions', 'refresh_token_hash')
    op.drop_constraint('owner_payment_records_commercial_invoice_id_fkey', 'owner_payment_records', type_='foreignkey')
    op.drop_column('owner_payment_records', 'commercial_invoice_id')
    op.drop_constraint('owner_customers_converted_from_lead_id_fkey', 'owner_customers', type_='foreignkey')
    op.drop_column('owner_customers', 'converted_from_lead_id')
    op.drop_table('owner_commission_payout_lines')
    op.drop_index('uq_commission_ledger_one_entry_per_payment', table_name='owner_commission_ledger_entries', postgresql_where=sa.text('reversal_of_ledger_entry_id IS NULL'))
    op.drop_table('owner_commission_ledger_entries')
    op.drop_table('owner_commercial_refunds')
    op.drop_table('owner_subscription_device_policy_overrides')
    op.drop_table('owner_commercial_invoice_items')
    op.drop_table('owner_sales_order_lines')
    op.drop_table('owner_commercial_invoices')
    op.drop_table('owner_sales_orders')
    op.drop_table('owner_quote_lines')
    op.drop_table('owner_quotes')
    op.drop_table('owner_customer_locations')
    op.drop_table('owner_customer_interactions')
    op.drop_table('owner_customer_followups')
    op.drop_table('owner_management_note_visibility_grants')
    op.drop_table('owner_management_note_comments')
    op.drop_table('owner_lead_status_history')
    op.drop_table('owner_lead_product_interests')
    op.drop_table('owner_lead_notes')
    op.drop_table('owner_lead_interactions')
    op.drop_table('owner_lead_followups')
    op.drop_table('owner_lead_assignments')
    op.drop_table('owner_device_policy_platform_rules')
    op.drop_table('owner_shared_management_notes')
    op.drop_table('owner_leads')
    op.drop_table('owner_expenses')
    op.drop_table('owner_employee_presence_sessions')
    op.drop_table('owner_employee_commission_plan_assignments')
    op.drop_table('owner_device_policy_profiles')
    op.drop_table('owner_employee_profiles')
    op.drop_table('owner_commission_rule_versions')
    op.drop_table('owner_commission_payout_batches')
    op.drop_table('owner_expense_categories')
    op.drop_table('owner_daily_activity_snapshots')
    op.drop_table('owner_commission_plans')
    op.drop_table('owner_commercial_operations_idempotency_keys')
    # ### end Alembic commands ###
