"""phase 6 licensing activation service schema

Revision ID: 60f363ee66e8
Revises: 62e4adb0a7b9
Create Date: 2026-07-21 08:36:37.320620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '60f363ee66e8'
down_revision = '62e4adb0a7b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_external_idempotency_records',
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('request_fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('result_reference', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_status', sa.String(length=32), nullable=True),
    sa.Column('cached_response_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key_hash', 'operation_type', name='uq_idempotency_key_operation')
    )
    op.create_table('owner_offline_policies',
    sa.Column('policy_code', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('check_in_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('offline_grace_seconds', sa.Integer(), nullable=False),
    sa.Column('warning_start_seconds', sa.Integer(), nullable=False),
    sa.Column('hard_expiry_behavior', sa.String(length=64), nullable=False),
    sa.Column('clock_rollback_tolerance_seconds', sa.Integer(), nullable=False),
    sa.Column('assertion_refresh_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('emergency_extension_allowed', sa.Boolean(), nullable=False),
    sa.Column('emergency_extension_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_code')
    )
    op.create_table('owner_rate_limit_counters',
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_key', 'window_start', name='uq_ratelimit_bucket_window')
    )
    op.create_table('owner_security_nonce_records',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce', 'scope', name='uq_nonce_scope')
    )
    op.create_table('owner_service_health_events',
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_signing_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('owner_key_rotation_events',
    sa.Column('from_key_id', sa.String(length=64), nullable=True),
    sa.Column('to_key_id', sa.String(length=64), nullable=False),
    sa.Column('rotated_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rotated_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_license_offline_policy_assignments',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('offline_policy_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['offline_policy_id'], ['owner_offline_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id')
    )
    op.create_table('owner_activation_requests',
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('installation_id', sa.UUID(), nullable=True),
    sa.Column('device_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['owner_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_device_public_keys',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_device_key_id', sa.UUID(), nullable=True),
    sa.Column('last_proof_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_device_key_id'], ['owner_device_public_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('owner_signed_assertions',
    sa.Column('assertion_id', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('signing_key_id', sa.String(length=64), nullable=False),
    sa.Column('assertion_version', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assertion_id')
    )
    op.create_table('owner_entitlement_snapshots',
    sa.Column('assertion_id', sa.UUID(), nullable=False),
    sa.Column('entitlements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['owner_signed_assertions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assertion_id')
    )
    op.create_unique_constraint('uq_owner_licenses_key_secret_hmac', 'owner_licenses', ['key_secret_hmac'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_owner_licenses_key_secret_hmac', 'owner_licenses', type_='unique')
    op.drop_table('owner_entitlement_snapshots')
    op.drop_table('owner_signed_assertions')
    op.drop_table('owner_device_public_keys')
    op.drop_table('owner_activation_requests')
    op.drop_table('owner_license_offline_policy_assignments')
    op.drop_table('owner_key_rotation_events')
    op.drop_table('owner_signing_keys')
    op.drop_table('owner_service_health_events')
    op.drop_table('owner_security_nonce_records')
    op.drop_table('owner_rate_limit_counters')
    op.drop_table('owner_offline_policies')
    op.drop_table('owner_external_idempotency_records')
    # ### end Alembic commands ###
