"""initial owner schema

Revision ID: 62e4adb0a7b9
Revises: 
Create Date: 2026-07-21 02:31:17.276229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '62e4adb0a7b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_entitlement_definitions',
    sa.Column('entitlement_code', sa.String(length=64), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entitlement_code')
    )
    op.create_table('owner_login_attempts',
    sa.Column('email_attempted', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_permissions',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('owner_platforms',
    sa.Column('platform_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code')
    )
    op.create_table('owner_products',
    sa.Column('product_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('commercial_status', sa.String(length=32), nullable=False),
    sa.Column('pilot_status', sa.String(length=64), nullable=True),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('owner_release_channels',
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_code')
    )
    op.create_table('owner_roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('owner_staff_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('owner_addons',
    sa.Column('addon_code', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addon_code')
    )
    op.create_table('owner_audit_log',
    sa.Column('actor_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role_snapshot', sa.String(length=255), nullable=True),
    sa.Column('action_code', sa.String(length=96), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_public_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_state_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_customers',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('organization_type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('tax_identifier', sa.String(length=128), nullable=True),
    sa.Column('commercial_registration_reference', sa.String(length=128), nullable=True),
    sa.Column('primary_language', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('acquisition_source', sa.String(length=128), nullable=True),
    sa.Column('assigned_sales_staff_id', sa.UUID(), nullable=True),
    sa.Column('assigned_support_staff_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_sales_staff_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_support_staff_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_database_backup_records',
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('owner_app_version', sa.String(length=32), nullable=True),
    sa.Column('schema_revision', sa.String(length=64), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('initiated_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_mfa_credentials',
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id')
    )
    op.create_table('owner_plans',
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('billing_model', sa.String(length=32), nullable=False),
    sa.Column('billing_interval_months', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('included_device_count', sa.Integer(), nullable=False),
    sa.Column('max_device_count', sa.Integer(), nullable=True),
    sa.Column('support_level', sa.String(length=32), nullable=False),
    sa.Column('release_channel_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['release_channel_id'], ['owner_release_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('owner_product_platforms',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['owner_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'platform_id', name='uq_product_platform')
    )
    op.create_table('owner_product_versions',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('release_channel_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('financial_contract_version', sa.String(length=64), nullable=True),
    sa.Column('artifact_checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('is_current_stable', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['owner_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['release_channel_id'], ['owner_release_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'platform_id', 'version', name='uq_product_platform_version')
    )
    op.create_table('owner_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['owner_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['owner_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('owner_security_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('staff_user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_staff_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('role_codes', sa.Text(), nullable=False),
    sa.Column('invited_by_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('owner_staff_role_assignments',
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['owner_roles.id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_user_id', 'role_id', name='uq_staff_role')
    )
    op.create_table('owner_staff_sessions',
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('session_version_at_login', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('owner_system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('owner_addon_entitlements',
    sa.Column('addon_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_definition_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['owner_addons.id'], ),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['owner_entitlement_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addon_id', 'entitlement_definition_id', name='uq_addon_entitlement')
    )
    op.create_table('owner_customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=True),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_customer_contacts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('business_phone', sa.String(length=64), nullable=True),
    sa.Column('preferred_channel', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_customer_notes',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('author_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_mfa_recovery_codes',
    sa.Column('mfa_credential_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mfa_credential_id'], ['owner_mfa_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_plan_entitlements',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_definition_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['owner_entitlement_definitions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'entitlement_definition_id', name='uq_plan_entitlement')
    )
    op.create_table('owner_plan_prices',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('setup_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_subscriptions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=32), nullable=True),
    sa.Column('auto_renew_preference', sa.Boolean(), nullable=False),
    sa.Column('device_allowance', sa.Integer(), nullable=True),
    sa.Column('platform_allowance', sa.String(length=64), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('sales_owner_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('support_owner_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['sales_owner_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['support_owner_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_licenses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('allowed_platforms', sa.String(length=128), nullable=False),
    sa.Column('allowed_release_channel_id', sa.UUID(), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuing_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('key_prefix', sa.String(length=32), nullable=True),
    sa.Column('key_suffix_masked', sa.String(length=16), nullable=True),
    sa.Column('key_secret_hmac', sa.String(length=128), nullable=True),
    sa.Column('key_format_version', sa.Integer(), nullable=False),
    sa.Column('replaced_by_license_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('activation_policy_identifier', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allowed_release_channel_id'], ['owner_release_channels.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['issuing_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_payment_records',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recorded_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['verified_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_subscription_addons',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('addon_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['owner_addons.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_subscription_items',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_subscription_status_history',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_installations',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('installation_label', sa.String(length=128), nullable=True),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('release_channel_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activation_count', sa.Integer(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('support_notes', sa.Text(), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=128), nullable=True),
    sa.Column('device_public_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['owner_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['release_channel_id'], ['owner_release_channels.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_license_entitlements',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_definition_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['owner_entitlement_definitions.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_license_key_issuance_events',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('issued_by_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_format_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('owner_license_status_history',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_renewal_records',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('previous_end_date', sa.Date(), nullable=True),
    sa.Column('new_end_date', sa.Date(), nullable=False),
    sa.Column('previous_plan_id', sa.UUID(), nullable=True),
    sa.Column('new_plan_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('related_payment_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['new_plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['previous_plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['related_payment_record_id'], ['owner_payment_records.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_activation_events',
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('installation_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('originating_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('safe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_schema_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['originating_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_device_records',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=128), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_installation_status_history',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['owner_installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_installation_status_history')
    op.drop_table('owner_device_records')
    op.drop_table('owner_activation_events')
    op.drop_table('owner_renewal_records')
    op.drop_table('owner_license_status_history')
    op.drop_table('owner_license_key_issuance_events')
    op.drop_table('owner_license_entitlements')
    op.drop_table('owner_installations')
    op.drop_table('owner_subscription_status_history')
    op.drop_table('owner_subscription_items')
    op.drop_table('owner_subscription_addons')
    op.drop_table('owner_payment_records')
    op.drop_table('owner_licenses')
    op.drop_table('owner_subscriptions')
    op.drop_table('owner_plan_prices')
    op.drop_table('owner_plan_entitlements')
    op.drop_table('owner_mfa_recovery_codes')
    op.drop_table('owner_customer_notes')
    op.drop_table('owner_customer_contacts')
    op.drop_table('owner_customer_addresses')
    op.drop_table('owner_addon_entitlements')
    op.drop_table('owner_system_settings')
    op.drop_table('owner_staff_sessions')
    op.drop_table('owner_staff_role_assignments')
    op.drop_table('owner_staff_invitations')
    op.drop_table('owner_security_events')
    op.drop_table('owner_role_permissions')
    op.drop_table('owner_product_versions')
    op.drop_table('owner_product_platforms')
    op.drop_table('owner_plans')
    op.drop_table('owner_mfa_credentials')
    op.drop_table('owner_database_backup_records')
    op.drop_table('owner_customers')
    op.drop_table('owner_audit_log')
    op.drop_table('owner_addons')
    op.drop_table('owner_staff_users')
    op.drop_table('owner_roles')
    op.drop_table('owner_release_channels')
    op.drop_table('owner_products')
    op.drop_table('owner_platforms')
    op.drop_table('owner_permissions')
    op.drop_table('owner_login_attempts')
    op.drop_table('owner_entitlement_definitions')
    # ### end Alembic commands ###
