"""phase 8 milestone 4 pilot lifecycle and emergency extensions

Revision ID: 65397e1b63e1
Revises: 0b1d294dfb40
Create Date: 2026-07-26 09:38:43.058881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '65397e1b63e1'
down_revision = '0b1d294dfb40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_emergency_extensions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('incident_reference', sa.String(length=128), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['owner_licenses.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_pilot_records',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('pilot_start', sa.Date(), nullable=False),
    sa.Column('pilot_end', sa.Date(), nullable=False),
    sa.Column('allowed_device_count', sa.Integer(), nullable=False),
    sa.Column('allowed_workflows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_level', sa.String(length=32), nullable=True),
    sa.Column('sales_owner_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('support_owner_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('agreed_limitations', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('exit_rollback_plan', sa.Text(), nullable=True),
    sa.Column('conversion_decision', sa.String(length=32), nullable=False),
    sa.Column('extension_count', sa.Integer(), nullable=False),
    sa.Column('max_extensions_allowed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('converted_renewal_request_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['converted_renewal_request_id'], ['owner_renewal_requests.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['owner_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['sales_owner_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['support_owner_staff_user_id'], ['owner_staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_table('owner_pilot_extensions',
    sa.Column('pilot_record_id', sa.UUID(), nullable=False),
    sa.Column('extension_number', sa.Integer(), nullable=False),
    sa.Column('previous_end_date', sa.Date(), nullable=False),
    sa.Column('new_end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['pilot_record_id'], ['owner_pilot_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_pilot_status_history',
    sa.Column('pilot_record_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('changed_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['pilot_record_id'], ['owner_pilot_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_pilot_status_history')
    op.drop_table('owner_pilot_extensions')
    op.drop_table('owner_pilot_records')
    op.drop_table('owner_emergency_extensions')
    # ### end Alembic commands ###
