"""phase 8 milestone 1 renewal workflow and payment correction history

Revision ID: 8646da2df010
Revises: 60f363ee66e8
Create Date: 2026-07-26 04:17:04.648897

"""
from alembic import op
import sqlalchemy as sa


revision = '8646da2df010'
down_revision = '60f363ee66e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_payment_correction_history',
    sa.Column('payment_record_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('previous_internal_note', sa.Text(), nullable=True),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.Column('corrected_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['payment_record_id'], ['owner_payment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_renewal_requests',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('current_plan_id', sa.UUID(), nullable=False),
    sa.Column('requested_plan_id', sa.UUID(), nullable=True),
    sa.Column('current_term_start', sa.Date(), nullable=True),
    sa.Column('current_term_end', sa.Date(), nullable=True),
    sa.Column('proposed_term_start', sa.Date(), nullable=True),
    sa.Column('proposed_term_end', sa.Date(), nullable=True),
    sa.Column('date_rule', sa.String(length=64), nullable=True),
    sa.Column('billing_interval', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('current_plan_price_id', sa.UUID(), nullable=True),
    sa.Column('proposed_plan_price_id', sa.UUID(), nullable=True),
    sa.Column('commercial_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('adjustment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('device_allowance_before', sa.Integer(), nullable=True),
    sa.Column('device_allowance_after', sa.Integer(), nullable=True),
    sa.Column('sales_owner_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('finance_reviewer_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('applied_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('customer_confirmation_reference', sa.String(length=128), nullable=True),
    sa.Column('related_payment_record_id', sa.UUID(), nullable=True),
    sa.Column('applied_renewal_record_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['applied_renewal_record_id'], ['owner_renewal_records.id'], ),
    sa.ForeignKeyConstraint(['approved_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['current_plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['current_plan_price_id'], ['owner_plan_prices.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['owner_customers.id'], ),
    sa.ForeignKeyConstraint(['finance_reviewer_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['owner_products.id'], ),
    sa.ForeignKeyConstraint(['proposed_plan_price_id'], ['owner_plan_prices.id'], ),
    sa.ForeignKeyConstraint(['related_payment_record_id'], ['owner_payment_records.id'], ),
    sa.ForeignKeyConstraint(['requested_plan_id'], ['owner_plans.id'], ),
    sa.ForeignKeyConstraint(['sales_owner_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['owner_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('owner_renewal_request_status_history',
    sa.Column('renewal_request_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by_staff_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_staff_user_id'], ['owner_staff_users.id'], ),
    sa.ForeignKeyConstraint(['renewal_request_id'], ['owner_renewal_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_renewal_request_status_history')
    op.drop_table('owner_renewal_requests')
    op.drop_table('owner_payment_correction_history')
    # ### end Alembic commands ###
