"""phase9r_m10_release_authority_fields

Revision ID: 96429a63cb29
Revises: 13944658bddf
Create Date: 2026-08-04 10:55:15.647735

"""
from alembic import op
import sqlalchemy as sa


revision = '96429a63cb29'
down_revision = '13944658bddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner_product_versions', sa.Column('build_number', sa.Integer(), nullable=True))
    op.add_column('owner_product_versions', sa.Column('min_supported_version', sa.String(length=64), nullable=True))
    op.add_column('owner_product_versions', sa.Column('forced_upgrade_threshold', sa.String(length=64), nullable=True))
    op.add_column('owner_product_versions', sa.Column('artifact_size_bytes', sa.Integer(), nullable=True))
    # server_default backfills any existing rows as DRAFT (matches the
    # model's Python-level default) -- a bare NOT NULL add would fail
    # against a populated table. Dropped after backfill so future inserts
    # go through the ORM's own default, not a DB-level one left dangling.
    op.add_column('owner_product_versions', sa.Column('publication_state', sa.String(length=16), nullable=False, server_default='DRAFT'))
    op.alter_column('owner_product_versions', 'publication_state', server_default=None)
    op.add_column('owner_product_versions', sa.Column('created_by_staff_user_id', sa.UUID(), nullable=True))
    op.add_column('owner_product_versions', sa.Column('published_by_staff_user_id', sa.UUID(), nullable=True))
    op.add_column('owner_product_versions', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owner_product_versions', sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owner_product_versions', sa.Column('withdrawn_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'owner_product_versions', 'owner_staff_users', ['created_by_staff_user_id'], ['id'])
    op.create_foreign_key(None, 'owner_product_versions', 'owner_staff_users', ['published_by_staff_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner_product_versions', type_='foreignkey')
    op.drop_constraint(None, 'owner_product_versions', type_='foreignkey')
    op.drop_column('owner_product_versions', 'withdrawn_reason')
    op.drop_column('owner_product_versions', 'withdrawn_at')
    op.drop_column('owner_product_versions', 'published_at')
    op.drop_column('owner_product_versions', 'published_by_staff_user_id')
    op.drop_column('owner_product_versions', 'created_by_staff_user_id')
    op.drop_column('owner_product_versions', 'publication_state')
    op.drop_column('owner_product_versions', 'artifact_size_bytes')
    op.drop_column('owner_product_versions', 'forced_upgrade_threshold')
    op.drop_column('owner_product_versions', 'min_supported_version')
    op.drop_column('owner_product_versions', 'build_number')
    # ### end Alembic commands ###
