"""phase_9_5b_employee_invitation_draft

Revision ID: af7831a6dc4d
Revises: 3c0d51d82d8c
Create Date: 2026-08-01 09:15:58.942606

"""
from alembic import op
import sqlalchemy as sa


revision = 'af7831a6dc4d'
down_revision = '3c0d51d82d8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner_staff_invitations', sa.Column('employee_profile_draft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner_staff_invitations', 'employee_profile_draft')
    # ### end Alembic commands ###
