package com.actionaura.retail.licensing

import com.google.crypto.tink.subtle.Ed25519Sign
import com.google.crypto.tink.subtle.Ed25519Verify
import com.google.common.truth.Truth.assertThat
import org.junit.Test

/**
 * Pure-JVM (no Android framework, no Robolectric needed) proof that Tink's
 * subtle Ed25519 primitives produce standard RFC 8032 output -- raw 32-byte
 * public keys, raw 64-byte signatures, verifiable independent of any Tink
 * keyset/prefix framing. This is the exact property the whole cross-platform
 * protocol depends on: Owner's Python `cryptography` library must be able to
 * verify a signature this Kotlin code produces, and vice versa.
 *
 * This test file prints PUBKEY_B64/MESSAGE_B64/SIG_B64 to stdout specifically
 * so a real cross-language check can consume them: run
 *   ./gradlew :app:testDebugUnitTest --tests "*Ed25519CrossVerifyTest*"
 * capture the printed values, then feed them into a Python script using
 * `cryptography`'s Ed25519PublicKey.verify() to confirm real interop, not
 * just "the docs say this is RFC 8032." See
 * docs/licensing/phase7/android-device-key-storage-design.md.
 */
class Ed25519CrossVerifyTest {

    @Test
    fun `signature round trips within Tink itself`() {
        val keyPair = Ed25519Sign.KeyPair.newKeyPair()
        val message = "cross-language-interop-check".toByteArray(Charsets.UTF_8)
        val signature = Ed25519Sign(keyPair.privateKey).sign(message)

        assertThat(keyPair.publicKey.size).isEqualTo(32)
        assertThat(signature.size).isEqualTo(64)

        Ed25519Verify(keyPair.publicKey).verify(signature, message) // throws on failure
    }

    @Test
    fun `tampered message fails verification`() {
        val keyPair = Ed25519Sign.KeyPair.newKeyPair()
        val message = "original".toByteArray()
        val signature = Ed25519Sign(keyPair.privateKey).sign(message)

        var threw = false
        try {
            Ed25519Verify(keyPair.publicKey).verify(signature, "tampered".toByteArray())
        } catch (_: Exception) {
            threw = true
        }
        assertThat(threw).isTrue()
    }

    @Test
    fun `print vectors for python cross-verification`() {
        val keyPair = Ed25519Sign.KeyPair.newKeyPair()
        val message = "aura-phase7-cross-verify-fixed-message".toByteArray(Charsets.UTF_8)
        val signature = Ed25519Sign(keyPair.privateKey).sign(message)

        val b64 = java.util.Base64.getEncoder()
        println("PUBKEY_B64=" + b64.encodeToString(keyPair.publicKey))
        println("MESSAGE_B64=" + b64.encodeToString(message))
        println("SIG_B64=" + b64.encodeToString(signature))
    }

    @Test
    fun `verifies a signature produced by python cryptography library`() {
        // Fixed vector generated once by running:
        //   python -c "
        //   from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
        //   from cryptography.hazmat.primitives import serialization
        //   import base64
        //   pk = Ed25519PrivateKey.generate()
        //   pub = pk.public_key().public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)
        //   msg = b'aura-phase7-cross-verify-fixed-message'
        //   sig = pk.sign(msg)
        //   print(base64.b64encode(pub).decode(), base64.b64encode(msg).decode(), base64.b64encode(sig).decode())
        //   "
        // Proves the OTHER direction of interop: a signature Owner's own
        // Python stack produces verifies correctly against Tink's
        // Ed25519Verify, with no format translation needed.
        // Generated by the exact command in this test's docstring, on this
        // repo's own .venv (requirements/owner-server.txt's cryptography==43.0.1).
        val pubKeyB64 = "0Ifzof0MI6z6X3m92pM8YYgAf5rQitUmoAF1C7QwtpQ="
        val messageB64 = "YXVyYS1waGFzZTctY3Jvc3MtdmVyaWZ5LWZpeGVkLW1lc3NhZ2U="
        val sigB64 = "TYjQB3Qyiy5/J/Mh41lGcRttxD4WKhKkvaYBGWn87d7nmLc6SRqFOgQt3A+YaYFUDVWhNsV/57NlG/0eqlq/AA=="

        val b64 = java.util.Base64.getDecoder()
        Ed25519Verify(b64.decode(pubKeyB64)).verify(b64.decode(sigB64), b64.decode(messageB64))
    }
}
