package com.actionaura.retail.financial

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * M3.5 -- the real Python-to-Kotlin differential suite. Every expected
 * value below is transcribed verbatim from
 * mobile/aura-retail-unified/differential/python_reference_output.json,
 * which was generated by mobile/aura-retail-unified/differential/
 * generate_python_reference.py actually IMPORTING AND CALLING
 * products/retail/backend/core/retail/pricing.py -- not independently
 * re-derived, not hand-computed. Re-run that script any time
 * calculation_fixtures.json changes to regenerate the golden file this
 * test is transcribed from.
 *
 * Comparison is via Money's numeric equality (BigDecimal compareTo), not
 * string equality -- Python's `_money()` occasionally returns a signed
 * negative-zero float (e.g. `-0.0` for a discount_amount computed from a
 * negative gross times a positive rate), which is a real, harmless float-
 * formatting artifact of Python's own `Decimal.quantize()`/`float()`
 * conversion, not a business-meaningful difference; Money's `0.00` and
 * `-0.00` compare numerically equal, matching how the two systems'
 * downstream consumers (JSON APIs, receipts) already treat them.
 */
class PythonDifferentialTest {

    private fun m(v: String) = Money.parse(v).getOrNull()!!
    private fun q(v: String) = Quantity.parse(v).getOrNull()!!
    private fun rate(v: Double) = PercentageRate.trusted(v)
    private fun discount(v: Double) = PercentageRate.clampToDiscountRange(v)

    private fun assertLine(result: LineCalculation, gross: String, discountAmount: String, taxableAmount: String, tax: String, total: String) {
        assertEquals(m(gross), result.gross, "gross")
        assertEquals(m(discountAmount), result.discountAmount, "discountAmount")
        assertEquals(m(taxableAmount), result.taxableAmount, "taxableAmount")
        assertEquals(m(tax), result.tax, "tax")
        assertEquals(m(total), result.total, "total")
    }

    // -- calculate_line, golden values from python_reference_output.json --

    @Test fun cl01() = assertLine(calculateLine(m("100"), q("1"), discount(0.0), rate(15.0), TaxMode.AFTER_DISCOUNT), "100.0", "0.0", "100.0", "15.0", "115.0")
    @Test fun cl02() = assertLine(calculateLine(m("100"), q("1"), discount(10.0), rate(15.0), TaxMode.AFTER_DISCOUNT), "100.0", "10.0", "90.0", "13.5", "103.5")
    @Test fun cl03() = assertLine(calculateLine(m("100"), q("1"), discount(10.0), rate(15.0), TaxMode.BEFORE_DISCOUNT), "100.0", "10.0", "100.0", "15.0", "105.0")
    @Test fun cl04() = assertLine(calculateLine(m("100"), q("1"), discount(0.0), rate(10.0), TaxMode.AFTER_DISCOUNT), "100.0", "0.0", "100.0", "10.0", "110.0")
    @Test fun cl05() = assertLine(calculateLine(m("100"), q("1"), discount(0.0), rate(10.0), TaxMode.BEFORE_DISCOUNT), "100.0", "0.0", "100.0", "10.0", "110.0")
    @Test fun cl06() = assertLine(calculateLine(m("19.99"), q("3"), discount(5.0), rate(8.0), TaxMode.AFTER_DISCOUNT), "59.97", "3.0", "56.97", "4.56", "61.53")
    @Test fun cl07() = assertLine(calculateLine(m("10.1"), q("3"), discount(7.5), rate(8.25), TaxMode.AFTER_DISCOUNT), "30.3", "2.27", "28.03", "2.31", "30.34")
    @Test fun cl08() = assertLine(calculateLine(m("50"), q("2"), discount(10.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "100.0", "10.0", "90.0", "0.0", "90.0")

    // cl-09-zero-quantity: constructible via Quantity.zeroOrMore (the pure
    // calculateLine function itself, matching Python's calculate_line(),
    // performs no positivity validation -- that's a business rule enforced
    // one layer up, at Quantity.parse()/the repository, not here).
    @Test fun cl09() {
        val zeroQty = Quantity.zeroOrMore("0")!!
        assertLine(calculateLine(m("100"), zeroQty, discount(0.0), rate(10.0), TaxMode.AFTER_DISCOUNT), "0.0", "0.0", "0.0", "0.0", "0.0")
    }

    // cl-10-negative-quantity, cl-23-negative-zero-quantity: DELIBERATELY
    // NOT golden-tested here. Python's calculate_line() is a pure function
    // with no input validation and happily computes a negative total for a
    // negative quantity (real, confirmed: gross=-500.0, total=-550.0 in
    // the golden output). Kotlin's Quantity type makes a negative quantity
    // structurally unrepresentable anywhere in this codebase (there is no
    // public constructor that accepts one) -- a stronger guarantee than
    // Python's, not a weaker one, and not expressible as a same-shape
    // comparison. Documented as an intentional, structural difference in
    // docs/retail/unified_mobile/intentional-financial-differences.md,
    // not silently skipped.

    @Test fun cl11() = assertLine(calculateLine(m("25.5"), q("4"), discount(0.0), rate(5.0), TaxMode.AFTER_DISCOUNT), "102.0", "0.0", "102.0", "5.1", "107.1")
    @Test fun cl12() = assertLine(calculateLine(m("8"), q("1.5"), discount(0.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "12.0", "0.0", "12.0", "0.0", "12.0")
    @Test fun cl13() = assertLine(calculateLine(m("1"), q("1000000"), discount(0.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "1000000.0", "0.0", "1000000.0", "0.0", "1000000.0")
    @Test fun cl14() = assertLine(calculateLine(m("0"), q("5"), discount(10.0), rate(15.0), TaxMode.AFTER_DISCOUNT), "0.0", "0.0", "0.0", "0.0", "0.0")
    @Test fun cl15() = assertLine(calculateLine(m("-10"), q("1"), discount(0.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "-10.0", "-0.0", "-10.0", "-0.0", "-10.0")
    @Test fun cl16() = assertLine(calculateLine(m("19.999"), q("1"), discount(0.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "20.0", "0.0", "20.0", "0.0", "20.0")
    @Test fun cl17() = assertLine(calculateLine(m("100"), q("1"), discount(100.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "100.0", "100.0", "0.0", "0.0", "0.0")
    @Test fun cl18() = assertLine(calculateLine(m("100"), q("1"), discount(150.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "100.0", "100.0", "0.0", "0.0", "0.0")
    @Test fun cl19() = assertLine(calculateLine(m("100"), q("1"), discount(-10.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "100.0", "0.0", "100.0", "0.0", "100.0")
    @Test fun cl20() = assertLine(calculateLine(m("50"), q("2"), discount(10.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "100.0", "10.0", "90.0", "0.0", "90.0")
    @Test fun cl21() = assertLine(calculateLine(m("200"), q("1"), discount(25.0), rate(12.0), TaxMode.AFTER_DISCOUNT), "200.0", "50.0", "150.0", "18.0", "168.0")
    @Test fun cl22_unknownModeFallsBack() = assertLine(calculateLine(m("100"), q("1"), discount(10.0), rate(15.0), TaxMode.parseOrDefault("nonsense")), "100.0", "10.0", "90.0", "13.5", "103.5")
    @Test fun cl24() = assertLine(calculateLine(m("5.5"), q("10"), discount(0.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "55.0", "0.0", "55.0", "0.0", "55.0")
    @Test fun cl25_excessiveScalePrice() = assertLine(calculateLine(m("19.123456789"), q("1"), discount(0.0), rate(0.0), TaxMode.AFTER_DISCOUNT), "19.12", "0.0", "19.12", "0.0", "19.12")

    // -- calculate_invoice, golden values from python_reference_output.json --

    @Test fun ci01() {
        val r = calculateInvoice(m("200"), m("30"), rate(12.0), TaxMode.BEFORE_DISCOUNT)
        assertEquals(m("30.0"), r.discountAmount); assertEquals(m("200.0"), r.taxableAmount); assertEquals(m("24.0"), r.tax); assertEquals(m("194.0"), r.total)
    }

    @Test fun ci02_discountClampedToSubtotal() {
        val r = calculateInvoice(m("100"), m("150"), rate(10.0), TaxMode.AFTER_DISCOUNT)
        assertEquals(m("100.0"), r.discountAmount); assertEquals(m("0.0"), r.taxableAmount); assertEquals(m("0.0"), r.tax); assertEquals(m("0.0"), r.total)
    }

    @Test fun ci03_negativeDiscountClamped() {
        val r = calculateInvoice(m("100"), m("-20"), rate(10.0), TaxMode.AFTER_DISCOUNT)
        assertEquals(m("0.0"), r.discountAmount); assertEquals(m("100.0"), r.taxableAmount); assertEquals(m("10.0"), r.tax); assertEquals(m("110.0"), r.total)
    }

    // -- change, golden values from python_reference_output.json --

    @Test fun ch01_paymentExactlyEqual() = assertEquals(m("0.0"), calculateChange(m("100.0"), m("100.0")))
    @Test fun ch02_paymentAboveTotal() = assertEquals(m("5.0"), calculateChange(m("105.0"), m("100.0")))
    @Test fun ch03_paymentBelowTotal() = assertEquals(m("0.0"), calculateChange(m("80.0"), m("100.0"))) // max(0, ...) -- never negative
}
